language: ruby
sudo: required
dist: trusty
cache: bundler

before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install openssl libssl-dev
# Rebuild Ruby using the updated OpenSSL libraries which allows 2.5 to pass.
#  - rvm reinstall --disable-binary `rvm current`
# Fix a bug with Ruby 2.5: LoadError: cannot load such file -- bundler/dep_proxy
  - gem update --system
# This works for Ruby 2.3 and 2.4 but not 2.5 which doesn't seem to use the local gem.
  - gem install openssl

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
    - rvm: rbx-3
  allow_failures:
    - rvm: 2.5
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
